spring.application.name=kun.uz

spring.datasource.url=jdbc:postgresql://localhost:5432/kun_uz_db
spring.datasource.username=kun_uz
spring.datasource.password=kun_uz1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true