### Get All
GET localhost:8080/region/getAllRegions



### Save new region
POST localhost:8080/region/save
Content-Type: application/json

{
  "key": "TASHKENT region",
  "nameEn": "Tashkent region",
  "nameRu": "Ташкентская область",
  "nameUz": "Toshkent viloyati",
  "orderNumber": 2

}