### Create category
POST localhost:8080/api/v1/category/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJvcm1vbm92YXphbWF0OUBnbWFpbC5jb20iLCJzdWIiOiJvcm1vbm92YXphbWF0OUBnbWFpbC5jb20iLCJpYXQiOjE3ODE5NDEyNzgsImV4cCI6MTc4MjAyNzY3OH0.oC-H7W8S-iivTnjpI9v9Yanux6FSg8SouRKmR4E0tTTCV3NOzSUaArHn9cJLf_G2uO_BD8YgRoyMfNhDcoTOGw

{
  "orderNumber": 10,
  "nameUz": "Jamiyat 10",
  "nameRu": "Общество 10",
  "nameEn": "Society 10",
  "categoryKey": "society10"
}



### Update category
PUT localhost:8080/api/v1/category/admin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJiaWdtYW5nY29tQGdtYWlsLmNvbSIsInN1YiI6ImJpZ21hbmdjb21AZ21haWwuY29tIiwiaWF0IjoxNzUwMzAyODkxLCJleHAiOjE3NTAzODkyOTF9.jiApspABtlGP2x8zYvQkRnqqvl16o2VOIv_p6-8-Z9eQb0R5DsN3sjpWTADpijxEK0FvTVhWFe7iRRV9N9CwAA

{
  "orderNumber": 1,
  "nameUz": "Iqtisodiyot11",
  "nameRu": "Экономика11",
  "nameEn": "Economics11",
  "categoryKey": "iqtisodiyot11"
}


### Delete category
DELETE localhost:8080/api/v1/category/admin/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJiaWdtYW5nY29tQGdtYWlsLmNvbSIsInN1YiI6ImJpZ21hbmdjb21AZ21haWwuY29tIiwiaWF0IjoxNzUwMzAyODkxLCJleHAiOjE3NTAzODkyOTF9.jiApspABtlGP2x8zYvQkRnqqvl16o2VOIv_p6-8-Z9eQb0R5DsN3sjpWTADpijxEK0FvTVhWFe7iRRV9N9CwAA

### Get category list
GET localhost:8080/api/v1/category/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiJvcm1vbm92YXphbWF0OUBnbWFpbC5jb20iLCJzdWIiOiJvcm1vbm92YXphbWF0OUBnbWFpbC5jb20iLCJpYXQiOjE3ODE5NDEyNzgsImV4cCI6MTc4MjAyNzY3OH0.oC-H7W8S-iivTnjpI9v9Yanux6FSg8SouRKmR4E0tTTCV3NOzSUaArHn9cJLf_G2uO_BD8YgRoyMfNhDcoTOGw

### Get by lang
GET localhost:8080/api/v1/category/lang
Accept-Language: EN
